export default {
  START: 'INIT',
  TEMP_LOGOS: 'TEMP_LOGOS',
  SET_LOGOS: 'SET_LOGOS',
  SET_AMOUNT: 'SET_AMOUNT',
  SET_CURRENT_LOGO: 'SET_CURRENT_LOGO',
  SET_PREVIOUS_LOGO: 'SET_PREVIOUS_LOGO',
  SET_CHOICES: 'SET_CHOICES',
};
